### ISSUE TITLE
Support for new Geo features in Mongo DB 2.3+

### ISSUE THREAD

**Issue by kristianmandrup** [nofxx/mongoid-geospatial#20]
Very exciting new Geo features!! :)

http://docs.mongodb.org/manual/release-notes/2.4/#new-geospatial-indexes-with-geojson-and-improved-spherical-geometry

The 2.3 series adds a new type of geospatial index that supports improved spherical queries and GeoJSON. Create the index by specifying 2dsphere as the value of the field in the index specification, as any of the following:

```
db.collection.ensureIndex( { geo: "2dsphere" } )
db.collection.ensureIndex( { type: 1, geo: "2dsphere" } )
db.collection.ensureIndex( { geo: "2dsphere", type: 1 } )
```

In the first example you create a spherical geospatial index on the field named geo, in the second example, you create a compound index where the first field is a normal index, and the index of the second field is a spherical geospatial index. Unlike 2d indexes, fields indexed using the 2dsphere type do not have to be the first field in a compound index.

You must store data in the fields indexed using the 2dsphere index using the GeoJSON specification, at the moment. Support for storing points, in the form used by the existing 2d (i.e. geospatial) indexes is forthcoming. Currently, 2dsphere indexes only support the following GeoJSON shapes:

Point, as in the following:

`{ "type": "Point", "coordinates": [ 40, 5 ] }`

LineString, as in the following:

`{ "type": "LineString", "coordinates": [ [ 40, 5 ], [ 41, 6 ] ] }``

Polygon, as in the following:

```
{
  "type": "Polygon",
  "coordinates": [ [ [ 40, 5 ], [ 40, 6 ], [ 41, 6 ], [ 41, 5 ], [ 40, 5 ] ] ]
}
```

To query 2dsphere indexes, all current geospatial query operators with an additional $geoIntersects operator. Currently, all queries using the 2dsphere index must pass the query selector (e.g. $near, $geoIntersects) a GeoJSON document. With the exception of the GeoJSON requirement, the operation of $near is the same for 2dsphere indexes as 2d indexes.

`$geoIntersects`

The `$geoIntersects` selects all indexed points that intersect with the provided geometry. (i.e. Point, LineString, and Polygon.) You must pass $geoIntersects a document in GeoJSON format.

```
db.collection.find( { loc: { $geoIntersects:
                             { $geometry: { "type": "Point",
                                            "coordinates": [ 40, 5 ]
                             } } } } )
```

Would be nice to have initial support for this in the gem (or perhaps in `mongoid_spatial`) !?

**Comment by nofxx** [comment]
Check the README. All working fine in Mongoid 5!! =D

**Comment by kristianmandrup** [comment]
Sweet :)
