### ISSUE TITLE
Rails 4?

### ISSUE THREAD

**Issue by nielsen** [nofxx/mongoid-geospatial#30]
Is there any plan for Rails 4 support?

```
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    mongoid_geospatial (>= 0) ruby depends on
      activemodel (~> 3.1) ruby

    rails (= 4.0.0) ruby depends on
      activemodel (4.0.0)
```

**Comment by nofxx** [comment]
Rails 4 working ok.

@unkleara the idea is that in ruby, currently moped removed almost every 2d query, there's only sphere. I'm going to document this, but not going to write any code as mongoid 5 will drop moped.
