### ISSUE TITLE
Configuring with rgeo

### ISSUE THREAD

**Issue by mintuhouse** [nofxx/mongoid-geospatial#39]
````
$ Mongoid::Geospatial.with_rgeo!
#=> LoadError: cannot load such file -- mongoid_geospatial/ext/rgeo_spherical_point_impl
````
I get the the above error when I try to include ````with_rgeo!```` in initializer or rails conolse. I justed added ````
gem 'mongoid-geospatial', github: 'nofxx/mongoid-geospatial'
```` to Gemfile

**Comment by nofxx** [comment]
Hi @mintuhouse , please use the old gem: `mongoid_geospatial`. Notice the underscore:
   gem 'mongoid_geospatial'

I'm currently rewriting the master branch, actually waiting for some stuff on moped.
I'll let you know when the new gem is ready.

**Comment by mintuhouse** [comment]
Hi @nofxx,
Just wanted to confirm. I can start using the latest stable version of the gem right?

**Comment by nofxx** [comment]
Hello @mintuhouse , the hyphen version 4.0.1 is fixed iirc.
Now that mongoid is finally going v5 with the official mongo driver, I'll finish up and polish the gem.
Will let you know.
